server:
  port: 8080

spring:
  application:
    name: colaboradores-api
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/desafio?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: mysql

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
