apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: desafio
        - name: MYSQL_PASSWORD
          value: mysql
        - name: MYSQL_ROOT_PASSWORD
          value: mysql
        - name: MYSQL_USER
          value: root
        image: lrochadev/colaboradores-db
        name: colaboradores-db
        ports:
        - containerPort: 3306
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: microservices-colaboradores
      restartPolicy: Always
      volumes:
      - name: microservices-colaboradores
        persistentVolumeClaim:
          claimName: microservices-colaboradores
