apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: lrochadev/colaboradores-db:latest
          name: colaboradores-db
          envFrom:
            - configMapRef:
                name: app-configmap
          ports:
            - containerPort: 3306
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: microservices-colaboradores
      volumes:
        - name: microservices-colaboradores
          persistentVolumeClaim:
            claimName: microservices-colaboradores
