apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microservices-colaboradores
  labels:
    app: microservices-colaboradores
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
