apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: lrochadev/colaboradores-frontend
        name: colaboradores-frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
