apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: springappserver
  name: springappserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: springappserver
    spec:
      containers:
      - env:
        - name: DATABASE_HOST
          value: db
        - name: DATABASE_NAME
          value: desafio
        - name: DATABASE_PASSWORD
          value: mysql
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_USER
          value: root
        image: lrochadev/colaboradores-api
        name: colaboradores-api
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
