apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springappserver
  labels:
    app: springappserver
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: springappserver
    spec:
      containers:
        - image: lrochadev/colaboradores-api:latest
          name: colaboradores-api
          envFrom:
            - configMapRef:
                name: app-configmap
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
