apiVersion: v1
kind: Service
metadata:
  name: springappserver
  labels:
    app: springappserver
spec:
  selector:
    app: springappserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
